/*
 * generated by Xtext 2.25.0
 */
package streamblocks.cal.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import streamblocks.cal.CalRuntimeModule;
import streamblocks.cal.CalStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class CalIdeSetup extends CalStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new CalRuntimeModule(), new CalIdeModule()));
	}
	
}
